# Generated by Django 4.2.3 on 2024-01-23 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ucp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AddField(
            model_name="teacher",
            name="students",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teachers",
                to="ucp.student",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="classes",
            field=models.CharField(
                choices=[("CS", "CS"), ("ZBC", "ZBC"), ("XYZ", "XYZ")], max_length=100
            ),
        ),
    ]
