# Generated by Django 4.2.3 on 2024-01-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ucp", "0002_remove_student_teacher_teacher_students_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="students",
        ),
        migrations.AddField(
            model_name="teacher",
            name="students",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="teachers", to="ucp.student"
            ),
        ),
    ]
